<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  <Actions category="Scripts">

    <text>Eraser Mapper</text>
    
    <Action name="pykrita_eraser_mapper_toggle_eraser">
      <icon>draw-eraser</icon>
      <text>Set eraser mode</text>
      <whatsThis></whatsThis>
      <toolTip>Set eraser mode</toolTip>
      <iconText>Set eraser mode</iconText>
      <activationFlags></activationFlags>
      <activationConditions></activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
    
    <Action name="pykrita_eraser_mapper_freehand_brush_tool">
      <icon>krita_tool_freehand</icon>
      <text>Freehand Brush Tool</text>
      <whatsThis></whatsThis>
      <toolTip>Freehand Brush Tool</toolTip>
      <iconText>Freehand Brush Tool</iconText>
      <activationFlags></activationFlags>
      <activationConditions></activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>

  </Actions>
</ActionCollection>